homework_10/homework_10/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("", include("quotes.urls")),
    path("users/", include("users.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homework_10/quotes/urls.py
from django.urls import path

from . import views

app_name = "quotes"

urlpatterns = [
    path("", views.main, name="root"),
    path("<int:page>", views.main, name="root_paginate"),
    path("add_author/", views.add_author, name="add_author"),
    path("add_quote/", views.add_quote, name="add_quote"),
    path("author/<int:author_id>/", views.author_detail, name="author_detail"),
    path("tag/<str:tag_name>/", views.quotes_by_tag, name="quotes_by_tag"),
    path("quote/<int:pk>/delete/", views.delete_quote, name="delete_quote"),
    path("author/<int:pk>/delete/", views.delete_author, name="delete_author"),
]

homework_10/users/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView

from . import views
from .forms import LoginForm

app_name = "users"

urlpatterns = [
    path("signup/", views.RegisterView.as_view(), name="signup"),
    path(
        "signin/",
        LoginView.as_view(template_name="users/login.html", form_class=LoginForm),
        name="signin",
    ),
    path(
        "logout/",
        LogoutView.as_view(),
        name="logout",
    ),
]

homework_10/quotes/models.py
from django.db.models import (
    CASCADE,
    CharField,
    ForeignKey,
    ManyToManyField,
    Model,
    TextField,
)


# Create your models here.
class Author(Model):
    fullname = CharField(max_length=60)
    born_date = CharField(max_length=60)
    born_location = CharField(max_length=150)
    description = TextField()

    def __str__(self):
        return self.fullname


class Tag(Model):
    name = CharField(max_length=40, null=False, unique=True)

    def __str__(self):
        return self.name


class Quote(Model):
    quote = TextField()
    tags = ManyToManyField(Tag)
    author = ForeignKey(Author, on_delete=CASCADE, default=None, null=True)

homework_10/users/models.py
from django.db import models

# Create your models here.

homework_10/quotes/forms.py
from django.forms import (
    CharField,
    ModelChoiceField,
    ModelForm,
    Select,
    Textarea,
    TextInput,
)

from .models import Author, Quote, Tag


class AuthorForm(ModelForm):
    fullname = CharField(
        max_length=60,
        min_length=3,
        widget=TextInput(attrs={"class": "form-control "}),
    )
    born_date = CharField(
        max_length=60,
        min_length=6,
        widget=TextInput(attrs={"class": "form-control "}),
    )
    born_location = CharField(
        max_length=150,
        widget=TextInput(attrs={"class": "form-control "}),
    )
    description = CharField(
        widget=Textarea(attrs={"class": "form-control "}),
    )

    class Meta:
        model = Author
        fields = ("fullname", "born_date", "born_location", "description")


class TagForm(ModelForm):
    name = CharField(
        max_length=40,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )

    class Meta:
        model = Tag
        fields = ("name",)


class QuoteForm(ModelForm):
    quote = CharField(
        min_length=30,
        widget=Textarea(attrs={"class": "form-control"}),
    )
    tags = CharField(
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    author = ModelChoiceField(
        queryset=Author.objects.all(),
        widget=Select(attrs={"class": "form-control"}),
        to_field_name="fullname",
    )

    class Meta:
        model = Quote
        fields = ("quote", "tags", "author")

homework_10/users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import CharField, EmailField, EmailInput, PasswordInput, TextInput


class RegisterForm(UserCreationForm):
    username = CharField(
        max_length=16,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    email = EmailField(
        max_length=25, required=True, widget=EmailInput(attrs={"class": "form-control"})
    )
    password1 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )
    password2 = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class LoginForm(AuthenticationForm):
    username = CharField(
        max_length=16,
        min_length=3,
        required=True,
        widget=TextInput(attrs={"class": "form-control"}),
    )
    password = CharField(
        required=True, widget=PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ("username", "password")

homework_10/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render

from .forms import AuthorForm, QuoteForm
from .models import Author, Quote, Tag


# Create your views here.
def main(request, page=1):
    quotes = Quote.objects.all()
    per_page = 10
    padinator = Paginator(list(quotes), per_page)
    quotes_on_page = padinator.page(page)
    return render(request, "quotes/index.html", context={"quotes": quotes_on_page})


@login_required
def add_author(request):
    if request.method == "POST":
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/")
    else:
        form = AuthorForm()
    return render(request, "quotes/add_author.html", context={"form": form})


@login_required
def add_quote(request):
    if request.method == "POST":
        form = QuoteForm(request.POST)
        if form.is_valid():
            quote_data = form.cleaned_data["quote"]
            author_id = form.cleaned_data["author"]
            tag_names = form.cleaned_data["tags"].split(",")

            author = Author.objects.get(fullname=author_id)

            tags = []
            for tag_name in tag_names:
                tag, created = Tag.objects.get_or_create(name=tag_name.strip())
                tags.append(tag)

            quote = Quote.objects.create(quote=quote_data, author=author)
            quote.tags.set(tags)

            return redirect("/")
    else:
        form = QuoteForm()
    return render(request, "quotes/add_quote.html", context={"form": form})


def author_detail(request, author_id):
    author = get_object_or_404(Author, pk=author_id)
    return render(request, "quotes/author_detail.html", context={"author": author})


def quotes_by_tag(request, tag_name):
    tag = Tag.objects.get(name=tag_name)
    quotes = Quote.objects.filter(tags=tag)
    return render(
        request, "quotes/quotes_by_tag.html", context={"quotes": quotes, "tag": tag}
    )


@login_required
def delete_quote(request, pk):
    quote = get_object_or_404(Quote, pk=pk)
    if request.method == "POST":
        quote.delete()
        return redirect("/")
    return render(request, "quotes/quote_delete.html", {"quote": quote})


@login_required
def delete_author(request, pk):
    author = get_object_or_404(Author, pk=pk)
    if request.method == "POST":
        author.delete()
        return redirect("/")
    return render(request, "quotes/author_delete.html", {"author": author})

homework_10/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .forms import RegisterForm


class RegisterView(View):
    template_name = "users/register.html"
    form_class = RegisterForm

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="quotes:root")
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form": self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(
                request, f"Вітаємо {username}. Ваш акаунт успішно створено"
            )
            return redirect(to="users:signin")
        return render(request, self.template_name, {"form": form})

homework_10/quotes/templates/quotes/add_author.html
{% extends 'quotes/base.html' %}

{% block content %}
<h1>Add Author</h1>
<form method="post">
    {% csrf_token %}
    <label for="fullname">Full Name:</label><br>
    <input type="text" id="fullname" name="fullname"><br><br>

    <label for="born_date">Born Date:</label><br>
    <input type="text" id="born_date" name="born_date"><br><br>

    <label for="born_location">Born Location:</label><br>
    <input type="text" id="born_location" name="born_location"><br><br>

    <label for="description">Description:</label><br>
    <textarea id="description" name="description"></textarea><br><br>

    <button type="submit">Add Author</button>
</form>
{% endblock %}

homework_10/quotes/templates/quotes/add_quote.html
{% extends 'quotes/base.html' %}

{% block content %}
<title>Add Quote</title>
<h1>Add Quote</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Add Quote</button>
</form>
{% endblock %}

homework_10/quotes/templates/quotes/author_delete.html
{% extends 'quotes/base.html' %}

{% block content %}
<h1>Видалення автора</h1>
<p>Ви впевнені, що хочете видалити цього автора?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Так, видалити</button>
    <button href="/">Скасувати</button>
</form>


{% endblock %}

homework_10/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="author-details">
    <h3 class="author-title">{{author.fullname}}</h3>
    <p><strong>Born:</strong> <span class="author-born-date">{{author.born_date}}</span> <span
            class="author-born-location">in
            {{author.born_location}}</span></p>
    <p><strong>Description:</strong></p>
    <div class="author-description">
        {{author.description}}
    </div>
</div>

{% endblock %}

homework_10/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">

    <title>HW</title>
</head>

<body>
    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Quotes to HW-10</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                <form action="{% url 'users:logout' %}" method="post">
                    <button class="btn btn-secondary">Log out</button>
                    {% csrf_token %}
                    <a href="{% url 'quotes:add_quote' %}" class="btn btn-secondary">Add quote</a>
                    <a href="{% url 'quotes:add_author' %}" class="btn btn-secondary">Add author</a>
                </form>
                {% else %}
                <a href="{% url 'users:signup' %}" class="btn btn-secondary">SignUp</a>
                <a href="{% url 'users:signin' %}" class="btn btn-secondary">Login</a>
                {% endif %}
                </p>
            </div>
        </div>



        {% block content %} {% endblock %}

    </div>
</body>

</html>

homework_10/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %}

{% block content %}

<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
                </small>
                <a href="{% url 'quotes:delete_quote' quote.pk %}">(delete)</a>
                </small>
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:author_detail' quote.author.pk %}">(about)</a>
                <a href="{% url 'quotes:delete_author' quote.author.pk %}">(delete)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag}}">{{tag.name}}</a>
                {% endfor %}
            </div>

        </div>
        {% endfor %}

        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else%} # {% endif %}">
                        <span aria-hidden="true">←</span>Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>
    <div class="col-md-4 tags-box">

        <h2>Top Ten tags</h2>

        <span class="tag-item">
            <a class="tag" style="font-size: 28px" href="/tag/love/">love</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 26px" href="/tag/inspirational/">inspirational</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 26px" href="/tag/life/">life</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 24px" href="/tag/humor/">humor</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 22px" href="/tag/books/">books</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 14px" href="/tag/reading/">reading</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 10px" href="/tag/friendship/">friendship</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/friends/">friends</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 8px" href="/tag/truth/">truth</a>
        </span>

        <span class="tag-item">
            <a class="tag" style="font-size: 6px" href="/tag/simile/">simile</a>
        </span>


    </div>

</div>

{% endblock %}

homework_10/quotes/templates/quotes/quote_delete.html
{% extends 'quotes/base.html' %}

{% block content %}
<h1>Видалення цитати</h1>
<p>Ви впевнені, що хочете видалити цю цитату?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit">Так, видалити</button>
    <button href="/">Скасувати</button>
</form>


{% endblock %}

homework_10/quotes/templates/quotes/quotes_by_tag.html
{% extends 'quotes/base.html' %}

{% block content %}
<h1>Цитати за тегом "{{ tag.name }}"</h1>

{% if quotes %}
<div class="row">
    <div class="col-md-8">
        {% for quote in quotes %}
        <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
            <span class="text" itemprop="text">
                {{quote.quote}}
            </span>
            <span>by <small class="author" itemprop="author">{{quote.author.fullname}}</small>
                <a href="{% url 'quotes:author_detail' quote.author.pk %}">(about)</a>
            </span>
            <div class="tags">
                Tags:
                {% for tag in quote.tags.all %}
                <a class="tag" href="/tag/{{tag}}">{{tag.name}}</a>
                {% endfor %}
            </div>
        </div>
        {% endfor %}

        <nav>
            <ul class="pager">

                <li class="previous">
                    <a class="{% if not quotes.has_previous %} disabled {% endif %}"
                        href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else%} # {% endif %}">
                        <span aria-hidden="true">←</span>Previous
                    </a>
                </li>


                <li class="next">
                    <a class="{% if not quotes.has_next %} disabled {% endif %}"
                        href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}">
                        Next <span aria-hidden="true">→</span></a>
                </li>

            </ul>
        </nav>
    </div>

</div>
{% else %}
<p>Цитати за цим тегом відсутні.</p>
{% endif %}
{% endblock %}

homework_10/users/templates/users/login.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}" {% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}

homework_10/users/templates/users/register.html
{% extends 'quotes/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}